name: SQL Doctor CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  analyze-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.7'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run analyzer and generate report
        id: run_analyzer
        run: python only_preanalyze.py

      - name: Upload JSON results
        uses: actions/upload-artifact@v4
        with:
          name: sql-json-results
          path: results/*.json
